#pragma once

#include <cstddef>
#include <cstdint>

#include "device_buffer.hpp"
#include "morton_leaf_groups.hpp"
#include "tree_types.hpp"

constexpr int kMortonDimensions = 3;
constexpr int kMortonBitsPerAxis = 10;
constexpr int kMortonSpatialBits = kMortonDimensions * kMortonBitsPerAxis;

constexpr int kMortonStorageBits = 32;
constexpr int kMortonPaddingBits = kMortonStorageBits - kMortonSpatialBits;

constexpr int kOctreeMaxLevel = kMortonBitsPerAxis;

constexpr std::uint32_t kMortonSpatialMask = 0x3FFFFFFFu;

struct RadixToOctreePlanView
{
    int nRadixNodes = 0;
    int nOctreeNodes = 0;

    const int* radixLevel = nullptr;
    const int* edgeNodeCount = nullptr;
    const int* edgeNodeOffset = nullptr;
};

struct RadixToOctreePlan
{
    // Number of nodes in the binary radix tree: 2 * nLeaves - 1
    int nRadixNodes = 0;

    // Total number of octree nodes, including the explicit octree root at index zero
    int nOctreeNodes = 0;

    // Octree level associated with every radix node. Size: nRadixNodes
    DeviceBuffer<int> radixLevel;

     // Number of octree nodes generated by each radix edge.
    DeviceBuffer<int> edgeNodeCount;

    // Exclusive prefix sum of edgeNodeCount.
    DeviceBuffer<int> edgeNodeOffset;

    // Device-side error code used while building the plan.
    DeviceBuffer<int> errorCodeDevice;

    // Reusable CUB temporary storage.
    DeviceBuffer<std::byte> temporaryStorage;

    [[nodiscard]]
    RadixToOctreePlanView view() const noexcept
    {
        return {
            nRadixNodes,
            nOctreeNodes,
            radixLevel.data(),
            edgeNodeCount.data(),
            edgeNodeOffset.data()
        };
    }
};

void allocateRadixToOctreePlan(RadixToOctreePlan& plan, int nRadixNodes);

void buildRadixToOctreePlan(RadixToOctreePlan& plan, const Tree& radixTree, const MortonLeafGroups& groups);

void freeRadixToOctreePlan(RadixToOctreePlan& plan) noexcept;