#pragma once

#include <cstddef>
#include <cstdint>

#include "morton_leaf_groups.hpp"
#include "tree_types.hpp"

constexpr int kMortonDimensions = 3;
constexpr int kMortonBitsPerAxis = 10;
constexpr int kMortonSpatialBits = kMortonDimensions * kMortonBitsPerAxis;

constexpr int kMortonStorageBits = 32;
constexpr int kMortonPaddingBits = kMortonStorageBits - kMortonSpatialBits;

constexpr int kOctreeMaxLevel = kMortonBitsPerAxis;

constexpr std::uint32_t kMortonSpatialMask = 0x3FFFFFFFu;

struct RadixToOctreePlan
{
    // Number of nodes in the binary radix tree: 2 * nLeaves - 1
    int nRadixNodes = 0;

    // Total number of octree nodes, including the explicit octree root at index zero
    int nOctreeNodes = 0;

    // Octree level associated with every radix node. Size: nRadixNodes
    int* radixLevel = nullptr;

    // Number of octree nodes generated by the incoming edge of each radix node. For the radix root, the incoming edge is considered to start at the explicit octree root at level zero. Size: nRadixNodes
    int* edgeNodeCount = nullptr;

    // Exclusive prefix sum of edgeNodeCount. Nodes generated by radix node i will start at: 1 + edgeNodeOffset[i], the +1 reserves octree node zero for the root
    int* edgeNodeOffset = nullptr;

    // Device-side error code written by the validation kernel
    int* errorCodeDevice = nullptr;

    // Reusable CUB temporary storage
    void* temporaryStorage = nullptr;
    std::size_t temporaryStorageBytes = 0;
};

void allocateRadixToOctreePlan(RadixToOctreePlan& plan, int nRadixNodes);

void buildRadixToOctreePlan(RadixToOctreePlan& plan, const Tree& radixTree, const MortonLeafGroups& groups);

void freeRadixToOctreePlan(RadixToOctreePlan& plan);