#pragma once

#include <cstddef>
#include <cstdint>
#include <type_traits>

#include <thrust/device_vector.h>

#include "device_vector_utils.hpp"
#include "morton_leaf_groups.hpp"
#include "tree_types.hpp"

constexpr int kMortonDimensions = 3;
constexpr int kMortonBitsPerAxis = 10;
constexpr int kMortonSpatialBits = kMortonDimensions * kMortonBitsPerAxis;

constexpr int kMortonStorageBits = 32;
constexpr int kMortonPaddingBits = kMortonStorageBits - kMortonSpatialBits;

constexpr int kOctreeMaxLevel = kMortonBitsPerAxis;

constexpr std::uint32_t kMortonSpatialMask = 0x3FFFFFFFu;

// Trivially-copyable, non-owning kernel argument. RadixToOctreePlan owns every
// allocation.
template <typename Int, typename Byte> struct BasicRadixToOctreePlanDeviceView {
  int nRadixNodes = 0;
  int nOctreeNodes = 0;
  Int *radixLevel = nullptr;
  Int *edgeNodeCount = nullptr;
  Int *edgeNodeOffset = nullptr;
  Int *errorCode = nullptr;
  Byte *temporaryStorage = nullptr;
  std::size_t temporaryStorageBytes = 0;
};

using RadixToOctreePlanDeviceView =
    BasicRadixToOctreePlanDeviceView<int, unsigned char>;
using ConstRadixToOctreePlanDeviceView =
    BasicRadixToOctreePlanDeviceView<const int, const unsigned char>;
static_assert(std::is_trivially_copyable_v<RadixToOctreePlanDeviceView>);
static_assert(std::is_trivially_copyable_v<ConstRadixToOctreePlanDeviceView>);

struct RadixToOctreePlan {
  // Number of nodes in the binary radix tree: 2 * nLeaves - 1
  int nRadixNodes = 0;

  // Total number of octree nodes, including the explicit octree root at index
  // zero
  int nOctreeNodes = 0;

  // Octree level associated with every radix node. Size: nRadixNodes
  thrust::device_vector<int> radixLevel;

  // Number of octree nodes generated by the incoming edge of each radix node.
  // For the radix root, the incoming edge is considered to start at the
  // explicit octree root at level zero. Size: nRadixNodes
  thrust::device_vector<int> edgeNodeCount;

  // Exclusive prefix sum of edgeNodeCount. Nodes generated by radix node i will
  // start at: 1 + edgeNodeOffset[i], the +1 reserves octree node zero for the
  // root
  thrust::device_vector<int> edgeNodeOffset;

  // Device-side error code written by the validation kernel
  thrust::device_vector<int> errorCodeDevice;

  // Reusable CUB temporary storage
  thrust::device_vector<unsigned char> temporaryStorage;

  [[nodiscard]] RadixToOctreePlanDeviceView device_view() noexcept {
    return {nRadixNodes,
            nOctreeNodes,
            nbody::deviceData(radixLevel),
            nbody::deviceData(edgeNodeCount),
            nbody::deviceData(edgeNodeOffset),
            nbody::deviceData(errorCodeDevice),
            nbody::deviceData(temporaryStorage),
            temporaryStorage.size()};
  }

  [[nodiscard]] ConstRadixToOctreePlanDeviceView device_view() const noexcept {
    return {nRadixNodes,
            nOctreeNodes,
            nbody::deviceData(radixLevel),
            nbody::deviceData(edgeNodeCount),
            nbody::deviceData(edgeNodeOffset),
            nbody::deviceData(errorCodeDevice),
            nbody::deviceData(temporaryStorage),
            temporaryStorage.size()};
  }
};

void allocateRadixToOctreePlan(RadixToOctreePlan &plan, int nRadixNodes);

void buildRadixToOctreePlan(RadixToOctreePlan &plan, const Tree &radixTree,
                            const MortonLeafGroups &groups);

void freeRadixToOctreePlan(RadixToOctreePlan &plan);
